Repository hinerumasato/react-news, pull requests merged in 2024-06, with the labels that each got.

#10 #9 - fix: create NewsItemContainer to hold NewsItems
  src/components/assets/NewItem.css
  src/components/pages/NewsItem.tsx
  src/components/pages/NewsItemContainer.tsx
  src/interfaces/INewsItem.ts
  src/interfaces/INewsItemContainer.ts
Labels: fix

#14 #6 - Completed to create Home
  index.html
  package-lock.json
  package.json
  src/components/assets/css/SliderContainer.css
  src/components/assets/css/SliderItem.css
  src/components/assets/css/SubscribeNews.css
  src/components/assets/css/WaveBackground.css
  src/components/pages/SliderContainer.tsx
  src/components/pages/SliderItem.tsx
  src/components/pages/SubscribeNews.tsx
  src/components/pages/WaveBackground.tsx
  src/index.css
  src/interfaces/ISliderContainer.ts
  src/interfaces/ISliderItem.ts
  src/react-splide.d.ts
Labels: feature

#12 Refactor/11 refactor news code
  package-lock.json
  package.json
  src/components/layouts/Master.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/News/News.tsx
  src/components/pages/index.ts
  src/components/partials/index.ts
  src/components/vendors/News/NewsItem.tsx
  src/components/vendors/News/NewsItemContainer.tsx
  src/interfaces/INewsItem.ts
  src/interfaces/INewsItemContainer.ts
  src/interfaces/IRoute.ts
  src/routes/index.ts
  tsconfig.json
  vite.config.ts
Labels: refactor

#15 feat: create rss service complete, create unit test
  .env.example
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/components/pages/Home/Home.tsx
  src/services/RssService.test.ts
  src/services/RssService.ts
  tsconfig.json
  vite.config.ts
Labels: feature, system

#20 18 - Refactor: Add component into News complete
  src/components/assets/css/CategoryBar.css
  src/components/assets/css/NewItem.css
  src/components/pages/News/CategoryBar.tsx
  src/components/pages/News/News.tsx
  src/components/pages/SliderContainer.tsx
  src/components/pages/SliderItem.tsx
  src/components/vendors/News/NewsItem.tsx
  src/interfaces/ICategoryBar.ts
Labels: refactor

#23 refactor: news components
  package-lock.json
  src/components/assets/css/CategoryBar.css
  src/components/pages/News/CategoryBar.tsx
  src/components/pages/News/News.tsx
  src/components/vendors/Buttons/CategoryBarButton.tsx
  src/components/vendors/Waves/Waves.tsx
  src/components/vendors/index.ts
  src/constants/index.ts
  src/constants/rssCategories.ts
  src/interfaces/ICategoryBar.ts
Labels: refactor

#24 Feature/21 add data to home
  package-lock.json
  package.json
  src/assets/css/CategoryBar.scss
  src/assets/css/NewItem.scss
  src/assets/css/PaginatePage.scss
  src/assets/css/SliderContainer.scss
  src/assets/css/SliderItem.scss
  src/assets/css/SubscribeNews.scss
  src/assets/css/WaveBackground.scss
  src/components/pages/Home/Home.tsx
  src/components/pages/Home/SliderContainer.tsx
  src/components/pages/Home/SliderItem.tsx
  src/components/pages/Home/WaveBackground.tsx
  src/components/pages/News/CategoryBar.tsx
  src/components/partials/PaginatePage.tsx
  src/components/partials/SubscribeNews.tsx
  src/components/vendors/News/NewsItem.tsx
  src/components/vendors/News/NewsItemContainer.tsx
  src/customHooks/useGetNewsItems.ts
  src/interfaces/ICategory.ts
  src/interfaces/INewsItem.ts
  src/interfaces/IRssItem.ts
  src/interfaces/ISliderContainer.ts
  src/interfaces/ISliderItem.ts
Labels: feature

#25 Refactor news
  package-lock.json
  src/components/assets/css/CategoryBar.css
  src/components/pages/News/CategoryBar.tsx
  src/components/pages/News/News.tsx
  src/components/vendors/Buttons/CategoryBarButton.tsx
  src/components/vendors/Waves/Waves.tsx
  src/components/vendors/index.ts
  src/constants/index.ts
  src/constants/rssCategories.ts
  src/interfaces/ICategoryBar.ts
Labels: refactor

#29 Add header and footer
  package-lock.json
  public/logo/logo.png
  src/App.tsx
  src/assets/css/NewItem.scss
  src/components/layouts/Master.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/News/News.tsx
  src/components/partials/Footer.tsx
  src/components/partials/Footer/Footer.scss
  src/components/partials/Footer/Footer.tsx
  src/components/partials/Footer/FooterFeed.scss
  src/components/partials/Footer/FooterFeed.tsx
  src/components/partials/Header.tsx
  src/components/partials/Header/Header.scss
  src/components/partials/Header/Header.tsx
  src/components/partials/index.ts
  src/components/vendors/Logo/Logo.tsx
  src/components/vendors/Mark/Mark.tsx
  src/components/vendors/index.ts
  src/hooks/index.ts
  src/hooks/useFeeds.ts
  src/hooks/useTitle.ts
  src/index.css
Labels: feature
