Repository hinerumasato/react-news, pull requests merged in 2024-07, with the labels that each got.

#33 27 - Refactor: Add data to news
  package-lock.json
  package.json
  src/assets/css/CategoryBar.scss
  src/components/pages/Home/Home.tsx
  src/components/pages/Home/SliderContainer.tsx
  src/components/pages/Home/SliderItem.tsx
  src/components/pages/Home/WaveBackground.tsx
  src/components/pages/News/CategoryBar.tsx
  src/components/pages/News/News.tsx
  src/components/partials/Footer/Footer.tsx
  src/components/partials/Header/Header.tsx
  src/components/vendors/Loading/Loading.scss
  src/components/vendors/Loading/Loading.tsx
  src/components/vendors/Mark/Mark.tsx
  src/components/vendors/News/NewsItem.tsx
  src/components/vendors/News/NewsItemContainer.tsx
  src/hooks/useFeeds.ts
Labels: refactor

#37 36 - Chỉnh sửa trang Home hoàn tất
  src/assets/css/NewItem.scss
  src/components/pages/Home/FocusedNewsItem.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/Home/HomeNewsContainer.tsx
  src/components/pages/Home/SliderContainer.tsx
  src/components/pages/Home/SliderItem.tsx
  src/components/pages/News/News.tsx
  src/components/partials/Footer/Footer.tsx
  src/components/partials/SubscribeNews.tsx
  src/constants/rssCategories.ts
  src/hooks/useFeeds.ts
  src/hooks/useFetchHomeFeeds.ts
  src/interfaces/IHomeNews.ts
Labels: feature

#39 Crawl Data and Post Detail
  .env
  .env.example
  package-lock.json
  package.json
  src/components/pages/NewsDetail/NewsDetail.scss
  src/components/pages/NewsDetail/NewsDetail.tsx
  src/components/pages/index.ts
  src/components/vendors/Mark/Mark.tsx
  src/components/vendors/News/NewsItem.tsx
  src/components/vendors/index.ts
  src/constants/application.ts
  src/constants/rssCategories.ts
  src/enums/feedType.ts
  src/hooks/index.ts
  src/hooks/useCrawlData.ts
  src/hooks/useParseFeed.ts
  src/interfaces/IFeedDetail.ts
  src/interfaces/index.ts
  src/modules/dom-class/AFeed.ts
  src/modules/dom-class/DefaultFeedDom.ts
  src/modules/dom-class/EmagazineFeedDom.ts
  src/modules/dom-class/FeedDomFactory.ts
  src/modules/index.ts
  src/routes/index.ts
  src/services/RssService.test.ts
  src/utils/index.ts
  src/utils/urls.ts
Labels: feature

#45 #43 - Thêm TTS cho NewsDetails hoàn tất
  package-lock.json
  src/components/pages/Home/Home.tsx
  src/components/pages/NewsDetail/NewsDetail.tsx
  src/components/pages/NewsDetail/TtsAudio.tsx
  src/components/vendors/News/NewsItem.tsx
  src/routes/index.ts
Labels: feature

#48 #47 - Tạo chế độ darkmode hoàn tất
  package-lock.json
  package.json
  src/assets/css/CategoryBar.scss
  src/assets/css/FabButton.scss
  src/assets/css/NewItem.scss
  src/assets/css/SearchNews.scss
  src/assets/css/SliderItem.scss
  src/assets/css/SubscribeNews.scss
  src/assets/css/Weather.scss
  src/components/pages/News/CategoryBar.tsx
  src/components/pages/Search/SearchNews.tsx
  src/components/partials/Footer/Footer.scss
  src/components/partials/Header/Header.scss
  src/components/partials/Header/Header.tsx
  src/components/partials/Header/Weather.tsx
  src/components/vendors/Buttons/ThemeToggleButton.tsx
  src/components/vendors/Loading/Loading.scss
  src/components/vendors/Logo/Logo.tsx
  src/index.css
  src/main.tsx
  src/redux/actions.ts
  src/redux/middlewares.ts
  src/redux/store.ts
Labels: feature

#53 46 share facebook
  Dockerfile
  package-lock.json
  package.json
  src/components/layouts/Master.tsx
  src/components/pages/NewsDetail/NewsDetail.scss
  src/components/pages/NewsDetail/NewsDetail.tsx
  src/components/pages/NewsDetail/Social/Social.scss
  src/components/pages/NewsDetail/Social/Social.tsx
Labels: feature

#52 Tóm tắt tin tức hoàn tất
  src/components/pages/NewsDetail/NewsDetail.tsx
  src/components/pages/NewsDetail/SummaryNews.tsx
  src/components/pages/NewsDetail/TtsAudio.tsx
  src/components/vendors/News/NewsItem.tsx
  src/hooks/index.ts
  src/hooks/useSummary.ts
  src/index.css
Labels: feature

#56 feat: current position weather
  src/components/partials/Header/Weather.tsx
  src/components/partials/Header/useWeather.ts
  src/constants/application.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useCurrentLocation.ts
  src/hooks/useGetCity.ts
  src/hooks/useWeathers.ts
Labels: feature

#60 58 fix dark mode
  src/assets/css/Weather.scss
  src/components/pages/Home/FocusedNewsItem.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/NewsDetail/FontSize/ToggleFontSize.scss
  src/components/pages/NewsDetail/FontSize/ToggleFontSize.tsx
  src/components/pages/NewsDetail/NewsDetail.scss
  src/components/pages/NewsDetail/NewsDetail.tsx
  src/components/pages/NewsDetail/Social/Social.scss
  src/components/pages/NewsDetail/SummaryNews.tsx
  src/components/partials/Footer/FooterFeed.tsx
  src/components/vendors/News/NewsItem.tsx
  src/index.css
Labels: fix

#62 #61- refactor category bar hoàn tất
  src/assets/css/CategoryBar.scss
  src/components/pages/History/HistoryNews.tsx
  src/components/pages/News/CategoryBar.tsx
  src/components/vendors/Buttons/CategoryBarButton.tsx
Labels: refactor
